/**
 * @description Provides functions for handling the user login session.
 */
define( [],

	function() {
		return {
			/**
			 * @function
			 * @description Check whether the user is logged out or not.
			 * @return {Boolean} Logged out status.
			 */
			isLoggedOut: function() {
				return ( !document.cookie || document.cookie == '' );
			},

			/**
			 * @function
			 * @description Login the user by setting a cookie with the users Id.
			 * @param {String} userId The userId generated by MongoDB.
			 */
			login: function( userId ) {
				document.cookie = userId;
				console.log( 'Inloggad!' );
			},

			/**
			 * @function
			 * @description Logout the user by clearing the cookie.
			 */
			logout: function() {
				document.cookie = '';
			},

			/**
			 * @function
			 * @description Retrieve the logged in users Id.
			 * @return {String} The user Id.
			 */
			getUserId: function() {
				if ( this.isLoggedOut() ) {
					return null;
				}

				return document.cookie;
			}
		};
	}
);
